export const legendList = [
	{ text: "Pokaż wszystko", id: 'all' },
	{ text: "Ramen", id: 'ramen' },
	{ text: "Zestawy sushi", id: 'sushiSets' },
	{ text: "Futomaki", id: 'futomaki' },
	{ text: "California", id: 'california' },
	{ text: "Hosomaki", id: 'hosomaki' },
	{ text: "Nigiri", id: 'nigiri' },
	{ text: "Przystawki", id: 'appetizers' },
	{ text: "Tatary", id: 'tartars' },
	{ text: "Gunkany", id: 'gunkans' },
	{ text: "Sashimi", id: 'sashimi' },
	{ text: "O-Nigiri", id: 'oNigiri' },
	{ text: "Zupy Misoshiru", id: 'misoSoups' },
	{ text: "Dodatki", id: 'sides' },
]
